### PR TITLE
Add some scripts to aid in development with podman

### PR DESCRIPTION
**Pull request by bowlofeggs**
This commit creates a devel folder with two scripts that are
intended to aid repoSpanner developers.

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
For some reason, the tests seem to timeout when I run the test script. I'm not sure what is wrong, but we shouldn't merge this PR until we can figure that out.

@puiterwijk can you think of a reason the tests might get stuck when run in podman?

You can try it out by running ```build.sh``` and then ```test.sh```.

**Comment by bowlofeggs** [comment]
OK, I discovered that the tests run in about twice the time in podman than they do on the host. I ended up setting a longer timeout to get them to pass.

**Review by puiterwijk — APPROVED** [review]
Cool, thank you!

**Comment by bowlofeggs** [comment]
To make codacy happy, I am applying this patch to the first commit:

```
diff --git a/README.md b/README.md
index 705cfb4..33572fa 100644
--- a/README.md
+++ b/README.md
@@ -107,7 +107,6 @@ Done
 ```
 You can now replace on your node and restart repospanner instance
 
-
 ## Contribute
 
 If you would like to get involved in repoSpanner development, take a look at the
diff --git a/devel/CONTRIBUTE.md b/devel/CONTRIBUTE.md
index dceccfe..2dedaa1 100644
--- a/devel/CONTRIBUTE.md
+++ b/devel/CONTRIBUTE.md
@@ -22,7 +22,6 @@ You can use `pprof` to interpret the data:
 
        go tool pprof http://dev.example.com:8444
 
-
 ## Tests
 
 The project comes with a decent functional test suite.  Explore the
@@ -33,7 +32,6 @@ To run the full test suite, run from the main directory:
 
     $ go test ./...
 
-
 ## Contributions
 
 Contributions are most welcome. To send a patch, send a pull request to the project on github.
@@ -41,7 +39,6 @@ Please make sure to add a `Signed-Off-By` line in your git commit to indicate
 you agree to the Developer Certificate of Origin (DCO) as quoted below.
 To do this, simple add the "-s" flag to your git commit, like: `git commit -s`.
 
-
 ### Developer Certificate of Origin
 
 Developer Certificate of Origin
@@ -55,7 +52,6 @@ San Francisco, CA, 94129
 Everyone is permitted to copy and distribute verbatim copies of this
 license document, but changing it is not allowed.
 
-
 Developer's Certificate of Origin 1.1
 
 By making a contribution to this project, I certify that:
```

I also applied a similar patch to the second commit.

**Pull request merged**
