### PR TITLE
Create GitHub build.yml workflow

### PR DESCRIPTION
**Pull request by puiterwijk**

### CODE REVIEW

**Comment by bowlofeggs** [comment]
Whoah does GitHub have integrated CI now? ¿Que es?

**Comment by puiterwijk** [comment]
@bowlofeggs Sure does!

**Review by bowlofeggs — APPROVED** [review]
LGTM, though to be honest I know nothing about the GitHub build system ☺

**Comment by puiterwijk** [comment]
@bowlofeggs Heh, that makes two of us! This is actually my very first dive into [GitHub Actions](https://github.com/features/actions).

**Pull request merged**
